[package]
name = "d05"
version = "0.1.0"
authors = ["Julian Møller <git@jumoel.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
itertools = "0.9.0"
